
import Head from 'next/head'
import Link from 'next/link'
import { PublicHeader } from '@/components/law-tech/PublicHeader'
import { LawTechDeskStyles } from '@/components/LawTechDeskStyles'
import { LawTechIcon } from '@/components/LawTechIcons'
const tools=[{name:'OCR',href:'https://law-tech.dev/ocr/',icon:'materials',meta:'图片、扫描件与 PDF',external:true},{name:'引注',href:'https://law-tech.dev/citation/',icon:'writing',meta:'论文、作业与读书笔记',external:true},{name:'全文搜索',href:'/search',icon:'search',meta:'文章、课程与标签索引'},{name:'课程整理',href:'/desk/courses',icon:'courses',meta:'私人工作台入口'},{name:'写作',href:'/desk/writing',icon:'writing',meta:'草稿、材料与发布'},{name:'系统设置',href:'/desk/system',icon:'system',meta:'账号、同步与个人档案'}]
export default function ToolsPage(){return <><Head><title>工具 · law-tech.dev</title><meta name='description' content='Curacao 的工具入口。'/><meta name='theme-color' content='#f5f3eb'/></Head><main className='lawtech-public-page tools-app-page'><div className='public-aurora public-aurora-two' aria-hidden='true'/><PublicHeader active='tools'/><div className='public-shell'><section className='tools-app-window'><div className='system-window-chrome'><i className='system-window-light red'/><i className='system-window-light yellow'/><i className='system-window-light green'/><span className='system-app-title'>Tools</span></div><header className='tools-app-head'><h1>工具</h1><p>OCR、引注、搜索与写作相关入口集中在这里。</p></header><section className='tools-launchpad' aria-label='工具列表'>{tools.map(tool=><Link className='tool-app-card' href={tool.href} key={tool.name} rel={tool.external?'noreferrer':undefined}><span className='tool-app-icon'><LawTechIcon name={tool.icon} size={24}/></span><strong>{tool.name}</strong><small>{tool.meta}</small></Link>)}</section></section></div><style jsx>{`.tools-app-window{min-height:calc(100dvh - 178px);padding-bottom:28px}.tools-app-head{display:grid;gap:10px;padding:10px 28px 24px;border-bottom:1px solid rgba(23,35,29,.07)}.tools-app-head h1{margin:0;font-family:var(--display-serif);font-size:clamp(42px,5vw,64px);font-weight:610;letter-spacing:-.055em}.tools-app-head p{margin:0;max-width:620px;color:var(--muted);line-height:1.75}.tools-launchpad{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px;padding:24px 28px 0}.tool-app-card{display:grid;min-height:172px;align-content:start;gap:10px;border:1px solid rgba(255,255,255,.64);border-radius:24px;padding:18px;background:rgba(255,255,255,.26);box-shadow:inset 0 1px 0 rgba(255,255,255,.64);transition:transform .2s var(--ease),border-radius .2s ease,background .2s ease}.tool-app-card:hover{transform:translateY(-4px);border-radius:20px;background:rgba(255,255,255,.42)}.tool-app-icon{display:grid;place-items:center;width:48px;height:48px;border:1px solid rgba(255,255,255,.64);border-radius:17px;color:var(--leaf);background:rgba(255,255,255,.26)}.tool-app-card strong{margin-top:8px;font-family:var(--display-serif);font-size:28px;font-weight:610}.tool-app-card small{color:var(--muted);font-size:12px;line-height:1.6}`}</style></main><LawTechDeskStyles/></>}
ToolsPage.layout='bare'
